export const COURSES = [
  // Programming Fundamentals
  { title: "CS50's Introduction to Computer Science", provider: "Harvard", platform: "edX", url: "https://www.edx.org/cs50", level: "Beginner", duration: "11 weeks", price: "Free", rating: 4.9, skills: ["C", "Python", "SQL", "Algorithms", "Data Structures"], category: "Programming", description: "Harvard's famous intro to computer science covering abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development." },
  { title: "The Complete JavaScript Course 2024", provider: "Jonas Schmedtmann", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-javascript-course/", level: "Beginner", duration: "69 hours", price: "$89", rating: 4.7, skills: ["JavaScript", "ES6", "DOM", "Async", "OOP"], category: "Programming", description: "Master modern JavaScript from the beginning. Covers ES6+, OOP, async JS, modern tools, and real-world projects." },
  { title: "Python for Everybody", provider: "University of Michigan", platform: "Coursera", url: "https://www.coursera.org/specializations/python", level: "Beginner", duration: "8 months", price: "Free audit", rating: 4.8, skills: ["Python", "Data Analysis", "Web Scraping", "Databases"], category: "Programming", description: "Learn to Program and Analyze Data with Python. Develop programs to gather, clean, analyze, and visualize data." },

  // Web Development
  { title: "The Complete 2024 Web Development Bootcamp", provider: "Angela Yu", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-web-development-bootcamp/", level: "Beginner", duration: "65 hours", price: "$89", rating: 4.7, skills: ["HTML", "CSS", "JavaScript", "React", "Node.js", "MongoDB"], category: "Web Development", description: "Full-stack web development bootcamp covering frontend and backend. Build 16 real-world projects using modern technologies." },
  { title: "React - The Complete Guide", provider: "Maximilian Schwarzmüller", platform: "Udemy", url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/", level: "Intermediate", duration: "49 hours", price: "$89", rating: 4.6, skills: ["React", "Redux", "Hooks", "Next.js", "TypeScript"], category: "Web Development", description: "Dive into React, Redux, Hooks, React Router, Next.js, best practices, and build real-world applications from scratch." },
  { title: "Next.js & React - The Complete Guide", provider: "Maximilian Schwarzmüller", platform: "Udemy", url: "https://www.udemy.com/course/nextjs-react-the-complete-guide/", level: "Intermediate", duration: "40 hours", price: "$89", rating: 4.7, skills: ["Next.js", "React", "SSR", "API Routes", "Authentication"], category: "Web Development", description: "Build fullstack React applications with Next.js 14+, covering server components, routing, API routes, authentication, and deployment." },
  { title: "Node.js, Express, MongoDB & More: The Complete Bootcamp", provider: "Jonas Schmedtmann", platform: "Udemy", url: "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/", level: "Intermediate", duration: "42 hours", price: "$89", rating: 4.7, skills: ["Node.js", "Express", "MongoDB", "REST APIs", "Authentication"], category: "Web Development", description: "Master Node.js by building a real-world RESTful API with authentication, error handling, payments, and deployment." },
  { title: "Advanced CSS and Sass", provider: "Jonas Schmedtmann", platform: "Udemy", url: "https://www.udemy.com/course/advanced-css-and-sass/", level: "Intermediate", duration: "28 hours", price: "$89", rating: 4.8, skills: ["CSS", "Sass", "Flexbox", "Grid", "Animations"], category: "Web Development", description: "Take your CSS to the next level with advanced techniques like Flexbox, Grid, animations, and responsive design." },

  // Data Science & ML
  { title: "Machine Learning Specialization", provider: "Andrew Ng / Stanford", platform: "Coursera", url: "https://www.coursera.org/specializations/machine-learning-introduction", level: "Intermediate", duration: "3 months", price: "$49/month", rating: 4.9, skills: ["Machine Learning", "Python", "Linear Regression", "Neural Networks", "Scikit-learn"], category: "Data Science", description: "Andrew Ng's foundational ML course updated for 2023. Build ML models in Python using NumPy and scikit-learn." },
  { title: "Deep Learning Specialization", provider: "Andrew Ng / DeepLearning.AI", platform: "Coursera", url: "https://www.coursera.org/specializations/deep-learning", level: "Advanced", duration: "5 months", price: "$49/month", rating: 4.9, skills: ["Deep Learning", "Neural Networks", "CNN", "RNN", "TensorFlow"], category: "Data Science", description: "Master deep learning, understand how to build neural networks, and lead successful ML projects. Covers CNNs, RNNs, LSTMs, Transformers." },
  { title: "IBM Data Science Professional Certificate", provider: "IBM", platform: "Coursera", url: "https://www.coursera.org/professional-certificates/ibm-data-science", level: "Beginner", duration: "11 months", price: "$49/month", rating: 4.6, skills: ["Python", "SQL", "Data Analysis", "Machine Learning", "Data Visualization"], category: "Data Science", description: "Launch your career in data science. Master Python, SQL, data analysis, ML, and visualization using real tools and projects." },
  { title: "Python for Data Science and Machine Learning Bootcamp", provider: "Jose Portilla", platform: "Udemy", url: "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/", level: "Intermediate", duration: "25 hours", price: "$89", rating: 4.6, skills: ["Python", "NumPy", "Pandas", "Scikit-learn", "Machine Learning"], category: "Data Science", description: "Learn how to use Python for data science, machine learning, NLP and deep learning with real-world case studies." },
  { title: "Natural Language Processing Specialization", provider: "DeepLearning.AI", platform: "Coursera", url: "https://www.coursera.org/specializations/natural-language-processing", level: "Advanced", duration: "4 months", price: "$49/month", rating: 4.6, skills: ["NLP", "Transformers", "BERT", "Attention", "Sequence Models"], category: "Data Science", description: "Break into the NLP space. Master cutting-edge NLP techniques including attention models, sequence-to-sequence, and transformers." },
  { title: "Data Analyst Professional Certificate", provider: "Google", platform: "Coursera", url: "https://www.coursera.org/professional-certificates/google-data-analytics", level: "Beginner", duration: "6 months", price: "$49/month", rating: 4.8, skills: ["SQL", "R", "Tableau", "Data Cleaning", "Data Visualization"], category: "Data Science", description: "Prepare for a career in data analytics. Learn SQL, R, Tableau, and the data analysis process in less than 6 months." },

  // AI & Generative AI
  { title: "Generative AI with Large Language Models", provider: "DeepLearning.AI / AWS", platform: "Coursera", url: "https://www.coursera.org/learn/generative-ai-with-llms", level: "Advanced", duration: "3 weeks", price: "$49", rating: 4.7, skills: ["LLM", "GenAI", "Prompt Engineering", "Fine-tuning", "RLHF"], category: "AI", description: "Learn the fundamentals of how generative AI works and how to deploy it. Build LLM-based applications with best practices." },
  { title: "ChatGPT Prompt Engineering for Developers", provider: "DeepLearning.AI / OpenAI", platform: "DeepLearning.AI", url: "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/", level: "Intermediate", duration: "1 hour", price: "Free", rating: 4.8, skills: ["Prompt Engineering", "ChatGPT", "LLM", "OpenAI API"], category: "AI", description: "Learn how to apply LLMs in your own applications. Covers summarizing, inferring, transforming, and expanding text." },
  { title: "LangChain for LLM Application Development", provider: "DeepLearning.AI", platform: "DeepLearning.AI", url: "https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/", level: "Intermediate", duration: "1 hour", price: "Free", rating: 4.7, skills: ["LangChain", "LLM", "RAG", "Agents", "Vector DB"], category: "AI", description: "Build production LLM apps with LangChain. Covers models, prompts, parsers, memory, chains, and agents." },

  // DevOps & Cloud
  { title: "AWS Certified Solutions Architect", provider: "Stephane Maarek", platform: "Udemy", url: "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/", level: "Intermediate", duration: "27 hours", price: "$89", rating: 4.7, skills: ["AWS", "EC2", "S3", "VPC", "Cloud Architecture"], category: "Cloud", description: "Prepare for the AWS Certified Solutions Architect Associate exam with hands-on labs and practice questions." },
  { title: "Docker & Kubernetes: The Practical Guide", provider: "Maximilian Schwarzmüller", platform: "Udemy", url: "https://www.udemy.com/course/docker-kubernetes-the-practical-guide/", level: "Intermediate", duration: "23 hours", price: "$89", rating: 4.7, skills: ["Docker", "Kubernetes", "Containers", "Microservices", "DevOps"], category: "DevOps", description: "Learn Docker, Kubernetes and container orchestration with hands-on projects and real-world deployment scenarios." },
  { title: "Google Cloud Professional Cloud Architect", provider: "Google Cloud", platform: "Coursera", url: "https://www.coursera.org/professional-certificates/gcp-cloud-architect", level: "Advanced", duration: "6 months", price: "$49/month", rating: 4.7, skills: ["GCP", "Cloud Architecture", "Kubernetes", "BigQuery", "Networking"], category: "Cloud", description: "Get hands-on experience designing and managing cloud solutions with GCP. Prepare for the Professional Cloud Architect certification." },
  { title: "Terraform - Infrastructure as Code", provider: "Zeal Vora", platform: "Udemy", url: "https://www.udemy.com/course/hashicorp-certified-terraform-associate/", level: "Intermediate", duration: "14 hours", price: "$89", rating: 4.6, skills: ["Terraform", "IaC", "AWS", "DevOps", "Automation"], category: "DevOps", description: "Master Terraform and Infrastructure as Code. Prepare for the HashiCorp Certified Terraform Associate exam." },
  { title: "CI/CD with Jenkins, GitHub Actions & GitLab", provider: "In28Minutes", platform: "Udemy", url: "https://www.udemy.com/course/devops-fundamentals-ci-cd-with-aws-jenkins-kubernetes/", level: "Intermediate", duration: "20 hours", price: "$89", rating: 4.5, skills: ["Jenkins", "GitHub Actions", "CI/CD", "DevOps", "Automation"], category: "DevOps", description: "Build CI/CD pipelines with industry standard tools. Learn Jenkins, GitHub Actions, GitLab CI, and deployment strategies." },

  // Mobile Development
  { title: "iOS & Swift - The Complete iOS App Development", provider: "Angela Yu", platform: "Udemy", url: "https://www.udemy.com/course/ios-13-app-development-bootcamp/", level: "Beginner", duration: "60 hours", price: "$89", rating: 4.8, skills: ["Swift", "iOS", "SwiftUI", "Xcode", "Firebase"], category: "Mobile", description: "Learn iOS 15 app development from scratch. Build 25 apps including clones of popular apps like WhatsApp and Pokemon Go." },
  { title: "Flutter & Dart - The Complete Guide", provider: "Maximilian Schwarzmüller", platform: "Udemy", url: "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/", level: "Beginner", duration: "43 hours", price: "$89", rating: 4.6, skills: ["Flutter", "Dart", "Mobile", "iOS", "Android"], category: "Mobile", description: "Build native iOS and Android apps with a single codebase using Flutter and Dart. Includes Firebase integration." },
  { title: "React Native - The Practical Guide", provider: "Maximilian Schwarzmüller", platform: "Udemy", url: "https://www.udemy.com/course/react-native-the-practical-guide/", level: "Intermediate", duration: "35 hours", price: "$89", rating: 4.6, skills: ["React Native", "Mobile", "iOS", "Android", "Redux"], category: "Mobile", description: "Use React Native to build cross-platform mobile apps for iOS and Android. Covers navigation, state management, and deployment." },

  // Databases
  { title: "The Complete SQL Bootcamp", provider: "Jose Portilla", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-sql-bootcamp/", level: "Beginner", duration: "9 hours", price: "$89", rating: 4.7, skills: ["SQL", "PostgreSQL", "Databases", "Data Analysis"], category: "Databases", description: "Become an expert at SQL. Learn PostgreSQL, database design, joins, aggregate functions, and real-world queries." },
  { title: "MongoDB - The Complete Developer's Guide", provider: "Maximilian Schwarzmüller", platform: "Udemy", url: "https://www.udemy.com/course/mongodb-the-complete-developers-guide/", level: "Intermediate", duration: "17 hours", price: "$89", rating: 4.6, skills: ["MongoDB", "NoSQL", "Aggregation", "Indexes", "Schema Design"], category: "Databases", description: "Master MongoDB Development for Web & Mobile Apps. Aggregation Framework, Replica Sets, Transactions, and more." },

  // Design & UI/UX
  { title: "Google UX Design Professional Certificate", provider: "Google", platform: "Coursera", url: "https://www.coursera.org/professional-certificates/google-ux-design", level: "Beginner", duration: "6 months", price: "$49/month", rating: 4.8, skills: ["UX Design", "Figma", "Wireframing", "Prototyping", "User Research"], category: "Design", description: "Launch your career as a UX designer. Build a professional portfolio with real design projects." },
  { title: "Figma UI UX Design Essentials", provider: "Daniel Walter Scott", platform: "Udemy", url: "https://www.udemy.com/course/figma-ux-ui-design-user-experience-tutorial-course/", level: "Beginner", duration: "15 hours", price: "$89", rating: 4.7, skills: ["Figma", "UI Design", "UX Design", "Prototyping", "Design Systems"], category: "Design", description: "Learn Figma for UX/UI design from scratch. Master modern design workflows, prototyping, and handoff." },

  // Cybersecurity
  { title: "Google Cybersecurity Professional Certificate", provider: "Google", platform: "Coursera", url: "https://www.coursera.org/professional-certificates/google-cybersecurity", level: "Beginner", duration: "6 months", price: "$49/month", rating: 4.8, skills: ["Cybersecurity", "Network Security", "Python", "SQL", "Linux"], category: "Cybersecurity", description: "Start a career in cybersecurity. Learn to identify common risks, threats, and vulnerabilities as well as techniques to mitigate them." },
  { title: "The Complete Cyber Security Course", provider: "Nathan House", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1/", level: "Intermediate", duration: "12 hours", price: "$89", rating: 4.5, skills: ["Cybersecurity", "Network Security", "Encryption", "Privacy", "Hacking"], category: "Cybersecurity", description: "Volume 1: Hackers Exposed. Learn cyber security from a practical perspective. Volume covering privacy, anonymity, and more." },

  // Business & Soft Skills
  { title: "Product Management Fundamentals", provider: "Cole Mercer", platform: "Udemy", url: "https://www.udemy.com/course/productmanagementfundamentals/", level: "Beginner", duration: "5 hours", price: "$89", rating: 4.5, skills: ["Product Management", "Agile", "User Research", "Roadmaps", "Analytics"], category: "Business", description: "Become a Product Manager. Learn the fundamentals, frameworks, and tools used by top PM's at leading tech companies." },
  { title: "Google Project Management Certificate", provider: "Google", platform: "Coursera", url: "https://www.coursera.org/professional-certificates/google-project-management", level: "Beginner", duration: "6 months", price: "$49/month", rating: 4.8, skills: ["Project Management", "Agile", "Scrum", "Stakeholder Management", "Risk"], category: "Business", description: "Start your career in project management. Learn in-demand skills that help you become job-ready in 6 months." },
  { title: "Digital Marketing Specialization", provider: "University of Illinois", platform: "Coursera", url: "https://www.coursera.org/specializations/digital-marketing", level: "Beginner", duration: "8 months", price: "$49/month", rating: 4.6, skills: ["SEO", "Social Media Marketing", "Analytics", "Content Marketing", "Branding"], category: "Marketing", description: "Master strategic marketing concepts and tools to address brand communication in a digital world." },
  { title: "The Complete Financial Analyst Course", provider: "365 Careers", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-financial-analyst-course/", level: "Beginner", duration: "21 hours", price: "$89", rating: 4.5, skills: ["Finance", "Excel", "Financial Modeling", "Valuation", "Accounting"], category: "Finance", description: "Become a Financial Analyst - Excel, Accounting, Finance, Financial Modeling, and Valuation - all in one course." },

  // QA & Testing
  { title: "Selenium WebDriver with Java", provider: "Rahul Shetty", platform: "Udemy", url: "https://www.udemy.com/course/selenium-webdriver-with-java-testng-and-framework/", level: "Intermediate", duration: "48 hours", price: "$89", rating: 4.5, skills: ["Selenium", "Java", "Test Automation", "TestNG", "Maven"], category: "QA", description: "Complete Selenium with Java framework. Build robust, scalable test automation frameworks from scratch." },
  { title: "Cypress - Modern Automation Testing", provider: "Shrinivasan Manikanda", platform: "Udemy", url: "https://www.udemy.com/course/cypress-tutorial/", level: "Intermediate", duration: "10 hours", price: "$89", rating: 4.6, skills: ["Cypress", "JavaScript", "E2E Testing", "API Testing", "CI/CD"], category: "QA", description: "Master Cypress for end-to-end web automation. Learn modern testing practices including API testing and CI/CD integration." },
  { title: "API Testing with Postman & REST Assured", provider: "Rahul Shetty", platform: "Udemy", url: "https://www.udemy.com/course/postman-the-complete-guide/", level: "Intermediate", duration: "15 hours", price: "$89", rating: 4.6, skills: ["Postman", "API Testing", "REST", "Automation", "Newman"], category: "QA", description: "Complete guide to API Testing using Postman, Newman, and REST Assured. Covers automation, CI/CD, and real-world projects." },

  // Algorithms & CS Fundamentals
  { title: "Algorithms Specialization", provider: "Stanford", platform: "Coursera", url: "https://www.coursera.org/specializations/algorithms", level: "Advanced", duration: "4 months", price: "$49/month", rating: 4.8, skills: ["Algorithms", "Data Structures", "Graph Theory", "Dynamic Programming", "NP-Complete"], category: "Programming", description: "Master the fundamentals of the design and analysis of algorithms. Tim Roughgarden's classic course." },
  { title: "Grokking the Coding Interview", provider: "Educative", platform: "Educative.io", url: "https://www.educative.io/courses/grokking-the-coding-interview", level: "Intermediate", duration: "60 hours", price: "$79", rating: 4.7, skills: ["Data Structures", "Algorithms", "Coding Interview", "System Design", "Problem Solving"], category: "Programming", description: "Ace coding interviews at FAANG and top tech companies. Pattern-based approach to 150+ problems." },
  { title: "System Design Interview", provider: "ByteByteGo", platform: "ByteByteGo", url: "https://bytebytego.com/", level: "Advanced", duration: "Self-paced", price: "$179/year", rating: 4.8, skills: ["System Design", "Scalability", "Distributed Systems", "Architecture", "Interviews"], category: "Programming", description: "Prepare for system design interviews at top tech companies. Covers scalability, distributed systems, and real-world architectures." },

  // Blockchain & Web3
  { title: "Ethereum and Solidity: The Complete Developer's Guide", provider: "Stephen Grider", platform: "Udemy", url: "https://www.udemy.com/course/ethereum-and-solidity-the-complete-developers-guide/", level: "Intermediate", duration: "24 hours", price: "$89", rating: 4.6, skills: ["Blockchain", "Ethereum", "Solidity", "Smart Contracts", "Web3"], category: "Blockchain", description: "Use Solidity, Ethereum, and Blockchain to build decentralized applications. Includes smart contracts, testing, and deployment." },

  // Game Development
  { title: "Complete C# Unity Game Developer 3D", provider: "GameDev.tv", platform: "Udemy", url: "https://www.udemy.com/course/unitycourse2/", level: "Beginner", duration: "30 hours", price: "$89", rating: 4.7, skills: ["Unity", "C#", "Game Development", "3D", "Physics"], category: "Game Development", description: "Design & Develop Video Games. Code in C#. Build 2D & 3D Games for Your Own Unique Game Ideas." },

  // Soft Skills
  { title: "Successful Negotiation: Essential Strategies and Skills", provider: "University of Michigan", platform: "Coursera", url: "https://www.coursera.org/learn/negotiation-skills", level: "Beginner", duration: "17 hours", price: "Free audit", rating: 4.8, skills: ["Negotiation", "Communication", "Leadership", "Business Strategy"], category: "Soft Skills", description: "Learn a model of negotiation applicable in every country and every business situation. Includes practical exercises." },
  { title: "The Complete Communication Skills Master Class", provider: "TJ Walker", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-communication-skills-master-class-for-life/", level: "Beginner", duration: "31 hours", price: "$89", rating: 4.5, skills: ["Communication", "Public Speaking", "Presentation", "Leadership", "Interviewing"], category: "Soft Skills", description: "Communication Skills for Persuasion, Assertiveness and All Business Communication Needs." },
];
